# Generated by Django 4.1 on 2022-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
