# Generated by Django 4.1 on 2022-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(help_text='Contenido del comentario.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(help_text='Email del comentador del post.', max_length=254),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(help_text='Nombre de la persona que comenta el post.', max_length=80),
        ),
    ]
