# Generated by Django 4.1 on 2022-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comentario_contenido_alter_comentario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(help_text='Contenido del mensaje', max_length=1000),
        ),
    ]
