# Generated by Django 4.1 on 2023-01-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
