# Generated by Django 4.1 on 2023-03-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_fecha_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_actualizacion',
        ),
    ]
