# Generated by Django 4.1 on 2023-04-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_articulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
