# Generated by Django 4.1 on 2022-08-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='usuario',
            new_name='user',
        ),
    ]
