# Generated by Django 4.1 on 2022-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
