# Generated by Django 4.1 on 2022-08-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_certificado_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='ContactProfile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
