# Generated by Django 4.1 on 2022-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_blog_delete_contactprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
